services:
  app:
    build: .
    ports:
      - "4000:3000"
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    depends_on:
      - db
  
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - BBDDPostgreStock:/var/lib/postgresql/data
      #Esto guarda los datos de la BBDD en un volumen para que no se pierdan al reiniciar el contenedor
      #Imagen de DOCKER de una base de datos POSTGRESSQL
      - ./almacen_inicial.sql:/docker-entrypoint-initdb.d/almacen_inicial.sql
    ports:
        - "5432:5432"
        #Esto expone el puerto 5432 del contenedor para acceder a la base de datos desde el host
        #Guarda los datos iniciales en la base de datos al iniciar el contenedor para crear la estructura y datos iniciales
volumes:
  BBDDPostgreStock:
  #Volumen para almacenar los datos de la base de datos PostgreSQL
# Nombre del volumen: BBDDPostgreStock
# Ruta en el contenedor: /var/lib/postgresql/data
# Este volumen asegura que los datos de la base de datos persistan incluso si el contenedor
# External=true, solo si el volumen ya existe, no se crea uno nuevo, si no se pone nada o false, se crea uno nuevo
    